app {
  name = "zio-poc"
  http {
    host = "0.0.0.0"
    port = 8080
  }
  db {
    url      = "jdbc:h2:mem:ziodb;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=true"
    driver   = "org.h2.Driver"
    user     = "sa"
    password = ""
  }
  batch {
    chunkSize = 5
  }
}
