services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - bitonic
  app:
    build: .
    depends_on:
      - redis
    environment:
      APP_PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - bitonic

networks:
  bitonic:
    driver: bridge